project '/Users/deejordan/Desktop/twitter-clone-ios/TwitterClone.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TwitterClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterClone
  pod 'RealmSwift', '~>10'
end
